version: "3.7"
services:
  mariadb:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: erpnext
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql

  # Enable PostgreSQL only if you use it, see development/README.md for more information.
  # postgresql:
  #   image: postgres:11.8
  #   environment:
  #     POSTGRES_PASSWORD: 123
  #   volumes:
  #     - postgresql-data:/var/lib/postgresql/data

  redis-cache:
    image: redis:alpine

  redis-queue:
    image: redis:alpine

  redis-socketio:
    image: redis:alpine

  frappe:
    build: .
    command: sleep infinity
    environment:
      - SHELL=/bin/bash
    volumes:
      # Enable if you require git cloning
      - ${HOME}/.ssh:/home/frappe/.ssh
    working_dir: /workspace/development/frappe-bench
    ports:
      - 8000-8005:8000-8005
      - 9000-9005:9000-9005
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio
      - minio
  minio:
    image: quay.io/minio/minio:RELEASE.2022-06-25T15-50-16Z
    command: server --address ":9002" --console-address ":9003" /data
    restart: on-failure
    ports:
      - 9011:9003
      - 9012:9002
    volumes:
      - minio:/data:rw


volumes:
  mariadb-data:
  minio:
